name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate manifest
      run: npm run generate-manifest
    
    - name: Build
      run: npm run build
    
    - name: Test TypeScript compilation
      run: npx tsc --noEmit
    
    - name: Run tests
      run: npm test
    
    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
    
    - name: Check for build artifacts
      run: |
        if [ ! -f "build/index.js" ]; then
          echo "Build failed: build/index.js not found"
          exit 1
        fi
        if [ ! -f "generated/manifest.json" ]; then
          echo "Manifest generation failed: generated/manifest.json not found"
          exit 1
        fi
        echo "Build successful!"
    
    - name: Test manifest content
      run: |
        if [ ! -s "generated/manifest.json" ]; then
          echo "Manifest is empty"
          exit 1
        fi
        echo "Manifest generated successfully with $(jq '.capabilities.tools.count' generated/manifest.json) tools"