name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, dev]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - TypeScript type safety and best practices
            - API error handling and security concerns
            - Code organization and structure
            - Performance considerations
            - Documentation completeness
            - Test coverage and quality
            
            Focus on files in src/ and scripts/ directories. Be constructive and helpful in your feedback.
